package explore

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/sandstorm/dashica/lib/components/layout"
	"github.com/sandstorm/dashica/lib/dashboard/widget"
)

// handleFormModel serves the editor form model for every registered widget type
// plus the available layouts (docs section 4.3, 4.4). The per-widget structure
// (field order, editor kind, help text, enum options) is generated by
// dashica-gen from the widget structs — a new widget option appears here
// automatically. Defaults are NOT baked into the descriptor; they are derived
// here at request time by marshalling a zero-value factory instance, which is
// accurate by definition (whatever the constructor sets IS the default set).
func (e *exploreImpl) handleFormModel(w http.ResponseWriter, r *http.Request) error {
	descriptors := widget.WidgetDescriptors()
	widgets := make(map[string]widgetFormModel, len(descriptors))
	for name, d := range descriptors {
		inst, err := widget.NewWidgetByType(name)
		if err != nil {
			return fmt.Errorf("form model: %w", err)
		}
		defaults, err := json.Marshal(inst)
		if err != nil {
			return fmt.Errorf("form model: marshal defaults for %q: %w", name, err)
		}
		widgets[name] = widgetFormModel{WidgetDescriptor: d, Defaults: defaults}
	}

	resp := formModelResponse{Widgets: widgets, Layouts: layout.Names()}
	w.Header().Set("Content-Type", "application/json")
	return json.NewEncoder(w).Encode(resp)
}

// widgetFormModel is a widget's generated descriptor plus its runtime-derived
// default field values (the marshalled zero-value factory instance).
type widgetFormModel struct {
	widget.WidgetDescriptor
	Defaults json.RawMessage `json:"defaults"`
}

type formModelResponse struct {
	Widgets map[string]widgetFormModel `json:"widgets"`
	Layouts []string                   `json:"layouts"`
}
