package explore

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/sandstorm/dashica/lib/clickhouse"
	"github.com/sandstorm/dashica/lib/components/layout"
	"github.com/sandstorm/dashica/lib/dashboard/widget"
)

// handleFormModel serves the editor form model for every registered widget type
// plus the available layouts (docs section 4.3, 4.4). The per-widget structure
// (field order, editor kind, help text, enum options) is generated by
// dashica-gen from the widget structs — a new widget option appears here
// automatically. Defaults are NOT baked into the descriptor; they are derived
// here at request time by marshalling a zero-value factory instance, which is
// accurate by definition (whatever the constructor sets IS the default set).
func (e *exploreImpl) handleFormModel(w http.ResponseWriter, r *http.Request) error {
	descriptors := widget.WidgetDescriptors()
	widgets := make(map[string]widgetFormModel, len(descriptors))
	for name, d := range descriptors {
		inst, err := widget.NewWidgetByType(name)
		if err != nil {
			return fmt.Errorf("form model: %w", err)
		}
		defaults, err := json.Marshal(inst)
		if err != nil {
			return fmt.Errorf("form model: marshal defaults for %q: %w", name, err)
		}
		widgets[name] = widgetFormModel{WidgetDescriptor: d, Defaults: defaults}
	}

	resp := formModelResponse{Widgets: widgets, Layouts: layout.Names(), FieldKinds: fieldKinds}
	w.Header().Set("Content-Type", "application/json")
	return json.NewEncoder(w).Encode(resp)
}

// fieldKind describes one selectable kind of a SqlField / TimestampedField, with
// the human-facing intent label the editor shows instead of the raw serializer
// vocabulary (autoBucket/count/enum/expr). Keeping the labels + slot metadata on
// the server keeps Go the source of truth (docs UX plan (3)); the sql field
// vocabulary is small and stable, so this static table mirrors it directly.
type fieldKind struct {
	// Kind is the wire "kind" discriminator (matches lib/dashboard/sql).
	Kind string `json:"kind"`
	// Label is the intent-teaching display text, e.g. "Time bucket (automatic)".
	Label string `json:"label"`
	// RequiresColumn is true when the kind needs a column picked (autoBucket,
	// enum); false for count (needs none) and expr (free SQL).
	RequiresColumn bool `json:"requiresColumn,omitempty"`
	// ColumnClass is the column class the kind prefers, so the picker offers the
	// right columns first (clickhouse.ColumnClass*). Empty when class-agnostic.
	ColumnClass string `json:"columnClass,omitempty"`
	// Advanced hides the kind (and the alias input) behind the "advanced" toggle;
	// the golden path never needs it.
	Advanced bool `json:"advanced,omitempty"`
}

// fieldKinds is the intent vocabulary the editor's field pickers speak. Order is
// the golden-path order: the first non-advanced kind valid for a slot is its
// default (autoBucket for the timestamped X, count for a value/Y field).
var fieldKinds = []fieldKind{
	{Kind: "autoBucket", Label: "Time bucket (automatic)", RequiresColumn: true, ColumnClass: clickhouse.ColumnClassTemporal},
	{Kind: "count", Label: "Row count"},
	{Kind: "enum", Label: "Column (as category)", RequiresColumn: true, ColumnClass: clickhouse.ColumnClassCategorical},
	{Kind: "expr", Label: "Custom SQL expression", Advanced: true},
}

// widgetFormModel is a widget's generated descriptor plus its runtime-derived
// default field values (the marshalled zero-value factory instance).
type widgetFormModel struct {
	widget.WidgetDescriptor
	Defaults json.RawMessage `json:"defaults"`
}

type formModelResponse struct {
	Widgets    map[string]widgetFormModel `json:"widgets"`
	Layouts    []string                   `json:"layouts"`
	FieldKinds []fieldKind                `json:"fieldKinds"`
}
