package widget

// zz_generated.dashica.go (per-widget JSON serializers + group serializers) is
// generated by cmd/dashica-gen from the widget structs' field types and doc
// comments — see docs/2026-07-21-dynamic-widget-dashboard-ui.md §4.1.
//
// It is gitignored and regenerated on every build (same convention as templ's
// *_templ.go); `go generate ./...` runs before `go build` in .mise/tasks/build.
//
// No package argument is needed: `go generate` runs the command with the working
// directory set to this file's directory, and dashica-gen defaults to loading "."
// — so it targets whichever package holds this directive.
//
//go:generate go run github.com/sandstorm/dashica/cmd/dashica-gen
