# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: dashica-server
release:
  github:
    owner: sandstorm
    name: dashica
  name_template: '{{.Tag}}'
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/dashica-server
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
dockers_v2:
  - images:
      - ghcr.io/sandstorm/{{ .ProjectName }}
    tags:
      - "{{ .Version }}"
      - latest
    dockerfile: Dockerfile.goreleaser
    sboms: []
    #platforms:
    #  - linux/amd64
    #  - linux/arm64/v8
    #  - linux/arm64
    flags:
      - --pull
    labels:
      org.opencontainers.image.title: "dashica"
      org.opencontainers.image.description: "dashica"
      org.opencontainers.image.url: "https://github.com/sandstorm/dashica"
      org.opencontainers.image.source: "https://github.com/sandstorm/dashica"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.created: "{{ time \"2006-01-02T15:04:05Z07:00\" }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.licenses: MIT
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'