
clickhouse:

  default:
    url: http://127.0.0.1:28123
    user: admin
    password: password
    database: default

  alert_storage:
    url: http://127.0.0.1:28123
    user: admin
    password: password
    database: default

log:
  to_stdout: true
dev_mode: true

