
clickhouse:

  default:
    url: http://clickhouse:8123
    user: admin
    password: password
    database: default

  alert_storage:
    url: http://clickhouse:8123
    user: admin
    password: password
    database: default

log:
  to_stdout: true
dev_mode: true

