FROM node:25.0-bookworm-slim
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/dashica-server /usr/bin/

RUN mkdir -p /npm && mkdir -p /app/src && echo "Hello World" >> /app/src/index.md
COPY ./npm/dashica ./npm/dashica
RUN cd /npm/dashica && npm install


ADD ./package.json.goreleaser /app/package.json
WORKDIR /app
RUN cd /app && npm install

STOPSIGNAL SIGINT
# ENTRYPOINT ["/bin/bash"]
CMD ["/usr/local/bin/npm", "run", "run:noninteractive"]