
# !!! THIS FILE IS IN .gitignore
# !!! BECAUSE IT CONTAINS SENSITIVE PWs

clickhouse:

#  playground:
#    url: https://play.clickhouse.com:443
#    user: explorer
#    password:
#    database: default
#    query_file_patterns:
#      - /src/docs


  default:
    # for dashica backend
    url: http://127.0.0.1:28123

    # for connection via "dashica clickhouse-cli" command
    nativeHostPort: 127.0.0.1:29001
    user: admin
    password: password
    database: default
    query_file_patterns:
      - /content/__testing
      - /src/docs


  alert_storage:
    url: http://127.0.0.1:28123
    user: admin
    password: password
    database: default
    query_file_patterns:
      - /__testing

